Update dependencies and fix Windows compatibility on Python 3.12
pyauth/python-pkcs11 pull request #183
Opened 2024-09-30 05:13 UTC by joseavegaa

This is follow-up of the now closed PR #174. This new PR tries to update the PKCS#11 specification to the latest published version and brings compatibility to Python 3.12 on Windows. 

The specific changes of this PR are:
- Update PKCS#11 Specification to version 3.1, published by [OASIS Standard](https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/os/include/pkcs11-v3.1/) on 2023-07-23.
- Removed deprecated references to Py_UNICODE* and replaced them by wchar_t as suggested by [PEP-624](https://peps.python.org/pep-0624/#replace-py-unicode-with-wchar-t).
- Added compatibility to Python 3.12 in Windows by removing the Py_UNICODE* references. 
- Bump package version to 0.8.0.
- Fixes #159 
- Fixes #165 

The package has been tested on new virtual environments using Python 3.12 on Windows 11 with the asepkcs.dll (Athena Smartcard System ASE Card).

2024-09-30 07:25 UTC, mathiasertl requested changes

2024-09-30 07:25 UTC, mathiasertl commented on pyproject.toml
> +               "Topic :: System :: Hardware :: Hardware Drivers :: Token"
Only minor comment: please leave the indentation intact. Hard to say what you changed here?

2024-09-30 07:25 UTC, mathiasertl commented on extern/pkcs11.h
> + * Latest stage of narrative specification: https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/pkcs11-spec-v3.1.html
Distribution terms are no longer noted here. I think it's still good to keep them here, right?

2024-09-30 07:29 UTC, mathiasertl commented
To be transparent about the maintenance situation: I don't have any access to HSMs. I'm not sure about @kislyuk? 

This means that any changes cannot currently be tested with real HSMs.

2024-11-12 17:10 UTC, is-alnilam commented
@mathiasertl I can't promise anything ongoing, but I might be able to run the tests on Linux against AWS CloudHSMv2, if that would be of any use? Someone would have to note down exactly how to run the tests though! (I'd rather not try to work it out, get it wrong, and invalidate the results.)

2024-12-05 08:25 UTC, XobrekX commented
Any update on this pull request? I'd really love to see 0.8.0 being released and finally being able to use python 3.12 on my windows box.

2024-12-07 00:53 UTC, haagensen commented
I guess this means it won't work with Python 3.13 also?

2024-12-09 19:58 UTC, mathiasertl commented
This PR has minor changes requested, if they are implemented I can merge this.

Note however that I don't think I can upload releases to PyPI at the moment. @kislyuk do you have upload permissions by now?

2024-12-09 23:47 UTC, kislyuk commented
I do not. @danni can you please invite me to the python-pkcs11 package on PyPI?

2024-12-10 00:25 UTC, danni commented
Yes I can do that. Same username?

2024-12-10 03:13 UTC, kislyuk commented
Yes, my PyPI username is identical to my GitHub one.

On Mon, Dec 9, 2024 at 16:26 Danielle Madeley ***@***.***>
wrote:

> Yes I can do that. Same username?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pyauth/python-pkcs11/pull/183#issuecomment-2529907316>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGSOPNR2R54YTHQ6MG5J6L2EYYKNAVCNFSM6AAAAABPCOW5AOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRZHEYDOMZRGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-15 08:43 UTC, mathiasertl commented
My username is mati: https://pypi.org/user/mati/

2025-04-14 05:10 UTC, gilweis commented
Tested under 3.13 and it's ok.
Please upload the releases to PyPI 🙏

2025-05-02 13:12 UTC, joseavegaa commented
Hi! Are there any updates on this PR and if it will get merge? It adds support for the latest versions of Python, which is something that I really need.

2025-05-02 14:41 UTC, kislyuk commented on pyproject.toml
> +version = "0.8.0"
Please do not change the version manually, it will be changed automatically by the release process.

2025-05-02 14:42 UTC, kislyuk requested changes
Changes to setup.py need to be reverted before this PR can be merged.

2025-05-08 19:46 UTC, xues-d commented
@mathiasertl - You can test via an HSM simulator.  I typically use the Utimaco simulator which you can get for free you just have to make an account on their site.  They have a traditional one called Cryptoserver (latest version is 6.1) and a post quantum one.  The simulators work on Windows or Linux (with Linux you don't need to install anything, simply have JDK, copy files, and run script - supports both OpenJDK and Oracle Java framework.  - https://utimaco.com/data-protection/simulators-and-trials.  I would like this update as well, have a tool working in Linux but cannot make an easy deployable version to Windows...

2025-06-19 19:54 UTC, MatthiasValvekens commented
FYI, the Windows linking issue was fixed in #202, and the build flow was taken care of by #204. I made another PR #205  just now to cover the header file upgrade + some related maintenance (that PR already accounts for the feedback given in this thread).

So I'm going to close this PR as obsolete, if you don't mind :).

2025-06-19 19:54 UTC, closed without merging